# Documentation: https://docs.getdbt.com/docs/get-started/connection-profiles

khanh-postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: satao.db.elephantsql.com
      port: 5432
      user: awahfgjj
      password: <POSTGRES_PASSWORD>
      dbname: awahfgjj 
      schema: ticketmaster
      threads: 4
      connect_timeout: 10 # default 10 seconds